### ISSUE TITLE
Hive- Elasticsearch Write Operation

### ISSUE THREAD

**Issue by sandesh2014** [elastic/elasticsearch-hadoop#409]
Hello,

I have been trying to write data from hive to elastic search. I have followed the following steps.
1. Add Jar to hive session (Using elasticsearch-hadoop-2.1.0.BUILD-SNAPSHOT.jar)
2. Created External table
3. INSERT OVERWRITE table existing_table select * from table1

But i'm getting the following error.
Query ID = hdfs_20150331103131_511875c9-efff-4e16-a12f-9f98f0931ade
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks is set to 0 since there's no reduce operator
Starting Job = job_1427797951492_0015, Tracking URL = http://126.32.16.10:8088/proxy/application_1427797951492_0015/
Kill Command = /usr/hdp/2.2.0.0-2041/hadoop/bin/hadoop job -kill job_1427797951492_0015
Hadoop job information for Stage-0: number of mappers: 0; number of reducers: 0
2015-03-31 10:31:39,953 Stage-0 map = 0%, reduce = 0%
Ended Job = job_1427797951492_0015 with errors
Error during job, obtaining debugging information...
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched:
Stage-Stage-0: HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec

**Comment by sandesh2014** [comment]
Can someone helpout

**Comment by costin** [comment]
First off, this is a issue tracker not the mailing list. In other words, use it to post bugs - it is not the appropriate place for questions or debugging.
Also please read the documentation, including the page on how to [get help](http://www.elastic.co/guide/en/elasticsearch/hadoop/master/troubleshooting.html#help). As it stands right now, your post doesn't provide enough information to understand what's going on.

Please see the section that I mentioned, provide enough information your script (which you haven't included) and also look into the hive logs since they contain the underlying exception and explanation on what's wrong.

And please use the mailing list until you're somewhat sure you have encountered a bug; there are significantly more folks on the list that can help, than here on the issue tracker.

**Comment by sandesh2014** [comment]
@costin Firstly Thanks for your response. Infact i'am facing the issue which even other mentioned in earlier issues. Hence it made me to post here. Regret for inconvenience. Here is the complete log. Appreciate if you can help out. Thanks in advance

2015-03-31 10:11:01,600 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Created MRAppMaster for application appattempt_1427797951492_0011_000001
2015-03-31 10:11:02,487 FATAL [main] org.apache.hadoop.conf.Configuration: error parsing conf job.xml
org.xml.sax.SAXParseException; systemId: file:///hadoop/yarn/local/usercache/hdfs/appcache/application_1427797951492_0011/container_1427797951492_0011_01_000001/job.xml; lineNumber: 843; columnNumber: 51; Character reference "&#0" is an invalid XML character.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:150)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2354)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2423)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2376)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2283)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:1110)
	at org.apache.hadoop.mapreduce.v2.util.MRWebAppUtil.initialize(MRWebAppUtil.java:51)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1421)
2015-03-31 10:11:02,490 FATAL [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Error starting MRAppMaster
java.lang.RuntimeException: org.xml.sax.SAXParseException; systemId: file:///hadoop/yarn/local/usercache/hdfs/appcache/application_1427797951492_0011/container_1427797951492_0011_01_000001/job.xml; lineNumber: 843; columnNumber: 51; Character reference "&#0" is an invalid XML character.
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2519)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2376)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2283)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:1110)
	at org.apache.hadoop.mapreduce.v2.util.MRWebAppUtil.initialize(MRWebAppUtil.java:51)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1421)
Caused by: org.xml.sax.SAXParseException; systemId: file:///hadoop/yarn/local/usercache/hdfs/appcache/application_1427797951492_0011/container_1427797951492_0011_01_000001/job.xml; lineNumber: 843; columnNumber: 51; Character reference "&#0" is an invalid XML character.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:150)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2354)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2423)
	... 5 more
2015-03-31 10:11:02,493 INFO [main] org.apache.hadoop.util.ExitUtil: Exiting with status 1

**Comment by costin** [comment]
This has been fixed in master (see #359) which you seem to be using. Make sure the same (latest) jar is used across all the nodes; it's quite common for an old version to be part of the classpath and for it to be loaded instead of the latest one.

**Comment by sandesh2014** [comment]
@costin Really thanks alot for your response. I have used elasticsearch-hadoop-2.1.0.BUILD-20150331.023432-348.jar as well. But still the same issue. Could you please suggest which version of jar should i use.

**Comment by costin** [comment]
See my previous comment on providing enough information - what's your environment, what type of distro are you using, Hadoop, Hive version, what does your script looks like, etc...
Any reason why you are not using gradle or maven and downloading the artifacts by hand?

**Comment by sandesh2014** [comment]
@costin  really thanks alot for your patience. I'm using hive -0.14 and hadoop - 2.6. Infact I'm using hortonworks 2.2.
Infact i have seen in documentation and it has been suggested to use "ADD JAR" to hive session. Hence im using it.

I'm a newbie to hadoop environment. Your help and guidance is highly thankful.

Really once again thanks alot for your patience, support.

**Comment by costin** [comment]
@sandesh2014 For the third time, what is your Hive script? I cannot help you if you don't provide basic information to replicate your issues.
Are you running against a VM or a remote cluster? Upload a gist with complete logs for your script - they contain information about the classpath, versions used, etc...

Please read the link that I gave you and the questions that I asked - having too much information is not an issue, having too little is.

**Comment by sandesh2014** [comment]
@costin Thanks alot for your help. Now, i cleaned up all Jars manually and now it is working fine with the latest build - elasticsearch-hadoop-2.1.0.BUILD-20150331.023432-348.jar

Really thanks alot for your help. 

Here is my script
CREATE EXTERNAL TABLE SAMPLE01_ELS
 (SAMID INT, SAMSOURCE STRING)
  STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
  TBLPROPERTIES('es.resource' = 'SAMPES/SAMPES',
  'es.nodes' = 'localhost:9200', 'es.index.auto.create' = 'true', 'es.write.operation' = 'index');

**Comment by costin** [comment]
Glad to hear it - what other version did you have in the classpath? Any idea how it got there? It might help in the future other users to track it down.

**Comment by sandesh2014** [comment]
@costin Earlier version was - elasticsearch-hadoop-2.1.0.BUILD-SNAPSHOT.jar. Even though i'm adding up a new version of Jar to hive session, the earlier version of jar is still residing on hadoop/lib, hive/lib path's.

I removed them manually and added new version of jar to hive session.

Now, this is working fine, able to create External table, INSERT data from internal table to external table, run job and able to automatically create index on elasticsearch.

Once again, thanks alot for your help.

**Comment by costin** [comment]
Glad to hear. Cheers!
